# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
          registry-url: 'https://npm.pkg.github.com'
      - name: npm install and npm run build
        run: |
          npm install
          npm run setversion 0.1.${{ github.run_number }}-${{github.job}}
          npm run build:ci
      - name: npm run publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.t2 }}
      - name: npm run publish2
        with:
          node-version: 12.8
          registry-url: 'https://registry.npmjs.org'
          token: '${{secrets.NPM_TOKEN}}'

      - name: npm run publish22
        run: npm run publish


      - name: npm run build:app:ci
        run: npm run build:app:ci

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: dist/kendo-jalali-date
          branch: main
          token: ${{ secrets.t2 }}
      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.t2 }}
      #     BRANCH: main
      #     FOLDER: dist/progress/kendo-jalali-date-picker
